%%%-------------------------------------------------------------------
%%% @author  <Kuleshov Alexander>
%%% @copyright (C) 2011, 
%%% @doc
%%%
%%% @end
%%% Created : 3 Feb 2011 by  <kuleshovmail@gmail.com>
%%%-------------------------------------------------------------------

-module(mime).

-vsn('0.1').
-author('kuleshovmail@gmail.com').

mime_version_header() ->
    "MIME-Version: 1.0 (Generated by EPmail) \r\n".

message(From, To, Subject) ->
    "From: " ++ From ++ "\r\n" ++
    "To: " ++ To ++ "\r\n" ++
    "Subject: " ++ Subject ++ "\r\n".
