%%%-------------------------------------------------------------------
%%% @author  <Kuleshov Alexander>
%%% @copyright (C) 2011, 
%%% @doc
%%%
%%% @end
%%% Created : 3 Feb 2011 by  <kuleshovmail@gmail.com>
%%%-------------------------------------------------------------------

-module(mime).

-vsn('0.2').
-author('kuleshovmail@gmail.com').

mime_version_header() ->
    "MIME-Version: 1.0 (Generated by EPmail) \r\n".

message(From, To, Subject) ->
    "From: " ++ From ++ "\r\n" ++
    "To: " ++ To ++ "\r\n" ++
    "Subject: " ++ Subject ++ "\r\n".

get_mime_type(File) ->
    case filename:extension(File) of
	".txt" ->
	    "text/plain";
	".jpeg"	->
	    "image/jpeg";
	".zip" ->
	    "application/x-compressed";
	".gz" ->
	    "application/x-compressed";
	".png" ->
	    "image/png";
	".bz2" ->
	    "application/x-bzip2";
	".doc" ->
	    "application/msword";
	".exe" ->
	    "application/octet-stream";
	".gzip" ->
	    "application/x-gzip";
	".htm" ->
	    "text/html";
	".html" ->
	    "text/html";
	".java" ->
	    "text/plain";
	".jpg" ->
	    "image/jpeg";
	".mp2" ->
	    "audio/mpeg";
	".mp3" ->
	    "audio/mpeg3";
	 ".mpeg"->
	    "video/mpeg";
	".rtf" ->
	    "application/rtf";
	".sh" ->
	    "application/x-bsh"
    end.
